export enum NotificationsType {
    NEW_ORDER = "NEW_ORDER",
    ORDER_CANCELLED = "ORDER_CANCELLED",
    ORDER_SHIPPED = "ORDER_SHIPPED",
    ORDER_IN_TRANSIT = "ORDER_IN_TRANSIT",
    ORDER_DELIVERED = "ORDER_DELIVERED",
    ORDER_REFUND = "ORDER_REFUND",
    NEW_NOTIFICATION = "NEW_NOTIFICATION"
}